# Generated by Django 4.1.4 on 2023-05-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_category_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='miscellaneous', max_length=200),
        ),
    ]
