# Generated by Django 4.1.4 on 2023-05-23 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_userreview_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
